In [62]:
import pandas as pd
df = pd.read_csv('2015QBs.csv')
df

,Rk,Player,Tm,Age,Pos,G,GS,QBrec,Cmp,Att,...,Y/G,Rate,QBR,Sk,Yds.1,NY/A,ANY/A,Sk%,4QC,GWD
0,1,Philip Rivers\RivePh00,SDG,34,QB,16,16,4-12-0,437,661,...,299.5,93.8,55.7,40,264,6.46,6.45,5.7,1.0,2.0
1,2,Drew Brees\BreeDr00,NOR,36,QB,15,15,7-8-0,428,627,...,324.7,101.0,70.4,31,235,7.04,7.26,4.7,1.0,2.0
2,3,Tom Brady *\BradTo00,NWE,38,QB,16,16,12-4-0,402,624,...,298.1,102.2,68.0,38,225,6.87,7.48,5.7,2.0,2.0
3,4,Eli Manning *\MannEl00,NYG,34,QB,16,16,6-10-0,387,618,...,277.0,93.6,60.5,27,157,6.63,6.74,4.2,1.0,2.0
4,5,Matt Ryan\RyanMa00,ATL,30,QB,16,16,8-8-0,407,614,...,286.9,89.0,69.6,30,203,6.81,6.35,4.7,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,82,Matt Moore\MoorMa01,MIA,31,NaN,1,0,NaN,1,1,...,14.0,118.7,98.3,0,0,14.00,14.00,0.0,NaN,NaN
82,83,Cairo Santos\SantCa01,KAN,24,NaN,16,0,NaN,1,1,...,0.2,79.2,NaN,0,0,3.00,3.00,0.0,NaN,NaN
83,84,Cecil Shorts\ShorCe00,HOU,28,WR,11,4,NaN,1,1,...,1.9,158.3,77.6,0,0,21.00,41.00,0.0,NaN,NaN
84,85,Scott Tolzien\TolzSc00,GNB,28,NaN,3,0,NaN,1,1,...,1.3,83.3,0.0,1,8,-2.00,-2.00,50.0,NaN,NaN
85,86,Bryan Walters\WaltBr00,JAX,28,NaN,11,1,NaN,0,1,...,0.0,39.6,1.9,0,0,0.00,0.00,0.0,NaN,NaN

In [63]:
df = df[:32]
df['Player'] = df['Player'].apply(lambda x: x.split('*')[0])
df['Player'] = df['Player'].apply(lambda x: x.split('\\')[0])
df['Player'] = df['Player'].apply(lambda x: x.split()[0] + " " + x.split()[1])

C:\Users\charl\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\charl\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\charl\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [64]:
def check_min_max(calc):
    if calc > 2.375:
        return 2.375
    elif calc < 0:
        return 0
    else:
        return calc

def find_nfl_rating(row):
    a = check_min_max(((row['Cmp']/row['Att']) - .3) * 5)
    b = check_min_max((row['Y/A'] - 3) * .25)
    c = check_min_max(((row['TD']/row['Att']) * 20))
    d = check_min_max((2.375 - ((row['Int']/row['Att']) *25)))
    return ((a+b+c+d)/6)*100

def find_wages_of_wins(row):
    return (row['Yds'] - row['Yds.1']) - (3*row['Att']) - (30*row['Int'])

def find_burke_rating(row):
    return (1.54337 * ((row['Yds'] - row['Yds.1']) / (row['Att'] + row['Sk']))) - (50.0957 * (row['Int']/row['Att']))

df['nfl_rating'] = df.apply(find_nfl_rating, axis=1)
df['wages_rating'] = df.apply(find_wages_of_wins, axis=1)
df['burke_rating'] = df.apply(find_burke_rating, axis=1)

C:\Users\charl\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\charl\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\charl\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [77]:
df1 = df.loc[: , ['Rk', 'Player', "Tm", 'Age', 'G', 'Yds', 'Yds.1', 'Cmp', 'Att', 'Sk', 'TD', "Int", 'nfl_rating', 'wages_rating', 'burke_rating']].set_index('Rk')
df1

,Player,Tm,Age,G,Yds,Yds.1,Cmp,Att,Sk,TD,Int,nfl_rating,wages_rating,burke_rating
Rk,,,,,,,,,,,,,,
1,Philip Rivers,SDG,34,16,4792,264,437,661,40,29,13,93.606278,2155,8.983917
2,Drew Brees,NOR,36,15,4870,235,428,627,31,32,11,101.170255,2424,9.992739
3,Tom Brady,NWE,38,16,4770,225,402,624,38,36,7,101.992521,2463,10.034127
4,Eli Manning,NYG,34,16,4432,157,387,618,27,35,14,93.706850,2001,9.094459
5,Matt Ryan,ATL,30,16,4591,203,407,614,30,21,16,89.115092,2066,9.210580
6,Blake Bortles,JAX,23,16,4428,320,355,606,51,35,18,88.193069,1750,8.162182
7,Matthew Stafford,DET,27,16,4262,251,398,592,44,32,13,96.976351,1845,8.633349
8,Ryan Tannehill,MIA,27,16,4208,420,363,586,45,24,12,88.823948,1670,8.239261
9,Derek Carr,OAK,24,16,3987,230,350,573,31,32,13,91.313991,1648,8.463516
10,Aaron Rodgers,GNB,32,16,3821,314,347,572,46,31,8,92.791375,1551,8.057611
11,Ryan Fitzpatrick,NYJ,33,16,3905,94,335,562,19,31,15,87.772835,1675,8.786477
12,Kirk Cousins,WAS,27,16,4166,186,379,543,26,29,11,101.692756,2021,9.780623
13,Carson Palmer,ARI,36,16,4671,151,342,537,25,35,11,104.596524,2579,11.386700
14,Jameis Winston,TAM,21,16,4042,190,312,535,27,22,15,84.373053,1797,9.173848
15,Sam Bradford,PHI,28,14,3725,200,346,532,28,19,14,86.387845,1509,8.396655
16,Cam Newton,CAR,26,16,3837,284,296,495,33,35,10,99.566498,1768,9.373560
17,Jay Cutler,CHI,32,15,3659,150,311,483,29,21,11,92.411146,1730,9.436615
18,Russell Wilson,SEA,27,16,4024,265,329,483,45,34,8,109.993099,2070,10.158000
19,Alex Smith,KAN,31,16,3486,235,307,470,45,20,7,95.328014,1631,8.996604
20,Ben Roethlisberger,PIT,33,12,3938,141,319,469,20,21,16,94.474947,1910,10.274978
21,Teddy Bridgewater,MIN,23,16,3231,307,292,447,44,14,9,88.571029,1313,8.182429
22,Joe Flacco,BAL,30,10,2791,124,266,413,16,14,12,83.281881,1068,8.139232
23,Andy Dalton,CIN,28,13,3250,118,255,386,20,25,7,106.167962,1764,10.997526
24,Tyrod Taylor,BUF,26,14,3035,212,242,380,36,20,6,99.451754,1503,9.682413
25,Marcus Mariota,TEN,22,12,2818,258,230,370,38,19,10,91.407658,1150,8.329952
26,Brian Hoyer,HOU,30,11,2606,185,224,369,25,19,7,91.513098,1104,8.533174
27,Nick Foles,STL,26,11,2052,98,190,337,14,7,10,69.043027,643,7.105347
28,Peyton Manning,DEN,39,10,2249,95,198,331,16,9,17,67.929255,651,7.007567
29,Andrew Luck,IND,26,7,1881,88,162,293,15,15,12,74.825085,554,6.932917
30,Josh McCown,CLE,36,8,2109,137,186,292,23,12,4,93.156393,976,8.975744
31,Blaine Gabbert,SFO,26,8,2031,164,178,282,25,10,7,86.161348,811,8.142391
32,Brock Osweiler,DEN,25,8,1967,151,170,275,23,10,6,86.628788,811,8.312238

In [72]:
dfn = df1.sort_values(by='nfl_rating', ascending=False).head(10)
dfn.index = range(1, 11)
dfn

,Player,Tm,Age,G,Yds,Yds.1,Cmp,Att,Sk,TD,Int,nfl_rating,wages_rating,burke_rating
1,Russell Wilson,SEA,27,16,4024,265,329,483,45,34,8,109.993099,2070,10.158000
2,Andy Dalton,CIN,28,13,3250,118,255,386,20,25,7,106.167962,1764,10.997526
3,Carson Palmer,ARI,36,16,4671,151,342,537,25,35,11,104.596524,2579,11.386700
4,Tom Brady,NWE,38,16,4770,225,402,624,38,36,7,101.992521,2463,10.034127
5,Kirk Cousins,WAS,27,16,4166,186,379,543,26,29,11,101.692756,2021,9.780623
6,Drew Brees,NOR,36,15,4870,235,428,627,31,32,11,101.170255,2424,9.992739
7,Cam Newton,CAR,26,16,3837,284,296,495,33,35,10,99.566498,1768,9.373560
8,Tyrod Taylor,BUF,26,14,3035,212,242,380,36,20,6,99.451754,1503,9.682413
9,Matthew Stafford,DET,27,16,4262,251,398,592,44,32,13,96.976351,1845,8.633349
10,Alex Smith,KAN,31,16,3486,235,307,470,45,20,7,95.328014,1631,8.996604

In [73]:
dfw = df1.sort_values(by='wages_rating', ascending=False).head(10)
dfw.index = range(1, 11)
dfw

,Player,Tm,Age,G,Yds,Yds.1,Cmp,Att,Sk,TD,Int,nfl_rating,wages_rating,burke_rating
1,Carson Palmer,ARI,36,16,4671,151,342,537,25,35,11,104.596524,2579,11.386700
2,Tom Brady,NWE,38,16,4770,225,402,624,38,36,7,101.992521,2463,10.034127
3,Drew Brees,NOR,36,15,4870,235,428,627,31,32,11,101.170255,2424,9.992739
4,Philip Rivers,SDG,34,16,4792,264,437,661,40,29,13,93.606278,2155,8.983917
5,Russell Wilson,SEA,27,16,4024,265,329,483,45,34,8,109.993099,2070,10.158000
6,Matt Ryan,ATL,30,16,4591,203,407,614,30,21,16,89.115092,2066,9.210580
7,Kirk Cousins,WAS,27,16,4166,186,379,543,26,29,11,101.692756,2021,9.780623
8,Eli Manning,NYG,34,16,4432,157,387,618,27,35,14,93.706850,2001,9.094459
9,Ben Roethlisberger,PIT,33,12,3938,141,319,469,20,21,16,94.474947,1910,10.274978
10,Matthew Stafford,DET,27,16,4262,251,398,592,44,32,13,96.976351,1845,8.633349

In [79]:
dfb = df1.sort_values(by='burke_rating', ascending=False).head(20)
dfb.index = range(1, 21)
dfb

,Player,Tm,Age,G,Yds,Yds.1,Cmp,Att,Sk,TD,Int,nfl_rating,wages_rating,burke_rating
1,Carson Palmer,ARI,36,16,4671,151,342,537,25,35,11,104.596524,2579,11.386700
2,Andy Dalton,CIN,28,13,3250,118,255,386,20,25,7,106.167962,1764,10.997526
3,Ben Roethlisberger,PIT,33,12,3938,141,319,469,20,21,16,94.474947,1910,10.274978
4,Russell Wilson,SEA,27,16,4024,265,329,483,45,34,8,109.993099,2070,10.158000
5,Tom Brady,NWE,38,16,4770,225,402,624,38,36,7,101.992521,2463,10.034127
6,Drew Brees,NOR,36,15,4870,235,428,627,31,32,11,101.170255,2424,9.992739
7,Kirk Cousins,WAS,27,16,4166,186,379,543,26,29,11,101.692756,2021,9.780623
8,Tyrod Taylor,BUF,26,14,3035,212,242,380,36,20,6,99.451754,1503,9.682413
9,Jay Cutler,CHI,32,15,3659,150,311,483,29,21,11,92.411146,1730,9.436615
10,Cam Newton,CAR,26,16,3837,284,296,495,33,35,10,99.566498,1768,9.373560
11,Matt Ryan,ATL,30,16,4591,203,407,614,30,21,16,89.115092,2066,9.210580
12,Jameis Winston,TAM,21,16,4042,190,312,535,27,22,15,84.373053,1797,9.173848
13,Eli Manning,NYG,34,16,4432,157,387,618,27,35,14,93.706850,2001,9.094459
14,Alex Smith,KAN,31,16,3486,235,307,470,45,20,7,95.328014,1631,8.996604
15,Philip Rivers,SDG,34,16,4792,264,437,661,40,29,13,93.606278,2155,8.983917
16,Josh McCown,CLE,36,8,2109,137,186,292,23,12,4,93.156393,976,8.975744
17,Ryan Fitzpatrick,NYJ,33,16,3905,94,335,562,19,31,15,87.772835,1675,8.786477
18,Matthew Stafford,DET,27,16,4262,251,398,592,44,32,13,96.976351,1845,8.633349
19,Brian Hoyer,HOU,30,11,2606,185,224,369,25,19,7,91.513098,1104,8.533174
20,Derek Carr,OAK,24,16,3987,230,350,573,31,32,13,91.313991,1648,8.463516